region             = "eu-west-3"
instance_type      = "t2.micro"
instance_key       = "frontwebserver"
creds              = "~/.aws/credentials"
vpc_cidr           = "178.0.0.0/16"
public_subnet_cidr = "178.0.10.0/24"
