doodle:
  usepad: true
  internalPadUrl: "http://localhost:9001/"
  externalPadUrl: "http://localhost:9001/"
  padApiKey: "19d89ca52bc0fa4f19d6325464d9d7a032649b9fa68c111514627081e2784b4a"
  organizermail: "olivier.barais@gmail.com"
  tmpfolder: "/tmp/excelFiles"
quarkus:
  jaeger:
    sampler-type: const
    sampler-param: 1
    service-name: doodle
  log:
    console:
      format: '%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n'

  datasource:
    db-kind: mysql
    username: tlc
    password: tlc
    jdbc:
      url: jdbc:mysql://localhost:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
#    database:
#      generation: none
#      globally-quoted-identifiers: true
  mailer:
    from: test@quarkus.io
#    host: smtp.sendgrid.net
    host: localhost
    port: 2525
#    port: 465
#    ssl: true

#    username: ""
#    password: ""
    mock: false
