version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ../.env

  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
