version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ../.env.prod
    networks:
      - intranet

  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    networks:
      - intranet

  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
    networks:
      - intranet

  quarkus:
    image: doodle/quarkus
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
      - "etherpad"
      - "mail"
    networks:
      - intranet
    env_file:
      - ../.env.prod

networks:
  intranet:
