
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ fuzzing-tuto ]
  pull_request:
    branches: [ fuzzing-tuto ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        # settings-path: ${{ github.workspace }}/api # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file api/pom.xml

    - name: Fuzzing with Javafuzz
      working-directory: ./api
      run: |
        mvn install
        wget -O jacocoagent.jar https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/javafuzz/-/raw/master/javafuzz-maven-plugin/src/main/resources/jacocoagent-exp.jar
        MAVEN_OPTS="-javaagent:jacocoagent.jar" mvn javafuzz:fuzz -DclassName=fr.istic.tlc.JavafuzzTestExample -Ddirs=CORPUS_DIR

    - name: Fuzzing with JQF and Zest
      working-directory: ./api
      run: mvn jqf:fuzz -Dclass=fr.istic.tlc.JQFTest.JQFTestExample -Dmethod=fuzzTest -Dtime=5s
